FROM node:argon

RUN mkdir -p /home/traincommander/api

WORKDIR /home/traincommander/api

RUN npm install -g strongloop

COPY api/package.json /home/traincommander/api
RUN npm install

COPY api /home/traincommander/api
ADD cmd_api.sh /bin/cmd_api

EXPOSE 4000 3000

CMD cmd_api
