-- MySQL Script generated by MySQL Workbench
-- jeu. 19 mai 2016 21:56:58 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TrainCommanderApi
-- -----------------------------------------------------
-- API database. Will not store user here ;)
-- 
DROP SCHEMA IF EXISTS `TrainCommanderApi` ;

-- -----------------------------------------------------
-- Schema TrainCommanderApi
--
-- API database. Will not store user here ;)
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrainCommanderApi` DEFAULT CHARACTER SET utf8 ;
USE `TrainCommanderApi` ;

-- -----------------------------------------------------
-- Table `TrainCommanderApi`.`Station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainCommanderApi`.`Station` (
  `idStation` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Location_Map` POINT NOT NULL,
  PRIMARY KEY (`idStation`),
  UNIQUE INDEX `idStation_UNIQUE` (`idStation` ASC),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  UNIQUE INDEX `Addresse_UNIQUE` (`Location_Map` ASC))
ENGINE = InnoDB
COMMENT = 'Refer all the station within the site.\nModification allowed only to admin.\nSelect for admin and search user (if needed but I don\'t think so, this table should be admin only)';


-- -----------------------------------------------------
-- Table `TrainCommanderApi`.`Trips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainCommanderApi`.`Trips` (
  `idTrips` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Departure` INT UNSIGNED NOT NULL,
  `Arrival` INT UNSIGNED NOT NULL,
  `IntermediateA` INT UNSIGNED NULL,
  `IntermediateB` INT UNSIGNED NULL,
  `IntermediateC` INT UNSIGNED NULL,
  `IntermediateD` INT UNSIGNED NULL,
  PRIMARY KEY (`idTrips`),
  UNIQUE INDEX `itTrips_UNIQUE` (`idTrips` ASC),
  UNIQUE INDEX `Departure_UNIQUE` (`Departure` ASC),
  UNIQUE INDEX `Arrival_UNIQUE` (`Arrival` ASC),
  UNIQUE INDEX `IntermediateA_UNIQUE` (`IntermediateA` ASC),
  UNIQUE INDEX `IntermediateB_UNIQUE` (`IntermediateB` ASC),
  UNIQUE INDEX `IntermediateC_UNIQUE` (`IntermediateC` ASC),
  UNIQUE INDEX `IntermediateD_UNIQUE` (`IntermediateD` ASC),
  INDEX `index9` (`Departure` ASC, `Arrival` ASC),
  CONSTRAINT `fk_Departure_Station`
    FOREIGN KEY (`Departure`)
    REFERENCES `TrainCommanderApi`.`Station` (`idStation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Arrival_Station`
    FOREIGN KEY (`Arrival`)
    REFERENCES `TrainCommanderApi`.`Station` (`idStation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_IntA_Station`
    FOREIGN KEY (`IntermediateA`)
    REFERENCES `TrainCommanderApi`.`Station` (`idStation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_IntB_Station`
    FOREIGN KEY (`IntermediateB`)
    REFERENCES `TrainCommanderApi`.`Station` (`idStation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_IntC_Station`
    FOREIGN KEY (`IntermediateC`)
    REFERENCES `TrainCommanderApi`.`Station` (`idStation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_IntD_Station`
    FOREIGN KEY (`IntermediateD`)
    REFERENCES `TrainCommanderApi`.`Station` (`idStation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'This table refer trips details (Start, Intermediate, Arrival)';


-- -----------------------------------------------------
-- Table `TrainCommanderApi`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainCommanderApi`.`Schedule` (
  `idSchedule` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Trip` INT UNSIGNED NOT NULL,
  `DTime` DATE NOT NULL,
  `ATime` DATE NOT NULL,
  `IATime` DATE NULL,
  `IBTime` DATE NULL,
  `ICTime` DATE NULL,
  `IDTime` DATE NULL,
  PRIMARY KEY (`idSchedule`),
  UNIQUE INDEX `idSchedule_UNIQUE` (`idSchedule` ASC),
  UNIQUE INDEX `Trip_UNIQUE` (`Trip` ASC),
  INDEX `Time` (`Trip` ASC, `DTime` ASC, `ATime` ASC)  COMMENT 'Quick Find Trip D&&A date',
  CONSTRAINT `fk_Schedule_Trip`
    FOREIGN KEY (`Trip`)
    REFERENCES `TrainCommanderApi`.`Trips` (`idTrips`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Store Shedule for trips';


-- -----------------------------------------------------
-- Table `TrainCommanderApi`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainCommanderApi`.`Cart` (
  `idCart` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Trip` INT UNSIGNED NOT NULL,
  `Quantity` INT UNSIGNED NOT NULL,
  `Schedule_ref` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCart`),
  UNIQUE INDEX `idCart_UNIQUE` (`idCart` ASC),
  UNIQUE INDEX `Trip_UNIQUE` (`Trip` ASC),
  UNIQUE INDEX `Quantity_UNIQUE` (`Quantity` ASC),
  UNIQUE INDEX `Schedule_ref_UNIQUE` (`Schedule_ref` ASC),
  CONSTRAINT `fk_Cart_Trip`
    FOREIGN KEY (`Trip`)
    REFERENCES `TrainCommanderApi`.`Trips` (`idTrips`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cart_Schedule`
    FOREIGN KEY (`Schedule_ref`)
    REFERENCES `TrainCommanderApi`.`Schedule` (`idSchedule`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainCommanderApi`.`Db_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainCommanderApi`.`Db_user` (
  `idUser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL COMMENT 'used as login',
  `Password` VARCHAR(45) NOT NULL COMMENT 'Store encrypted password as STRING',
  `Name` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `birth` DATE NULL DEFAULT NULL,
  `phone` INT(10) NULL,
  `addresse` VARCHAR(150) NULL,
  `city` VARCHAR(150) NULL,
  `country` VARCHAR(150) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  UNIQUE INDEX `email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrainCommanderApi`.`History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TrainCommanderApi`.`History` (
  `idHistory` INT UNSIGNED NOT NULL,
  `ref_iduser` INT UNSIGNED NOT NULL,
  `ref_shedule` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_date` DATE NOT NULL COMMENT 'Store date of trip in history',
  PRIMARY KEY (`idHistory`),
  UNIQUE INDEX `idHistory_UNIQUE` (`idHistory` ASC),
  UNIQUE INDEX `ref_iduser_UNIQUE` (`ref_iduser` ASC),
  UNIQUE INDEX `ref_cart_UNIQUE` (`ref_shedule` ASC),
  CONSTRAINT `fk_History_user`
    FOREIGN KEY (`ref_iduser`)
    REFERENCES `TrainCommanderApi`.`Db_user` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_History_shedule`
    FOREIGN KEY (`ref_shedule`)
    REFERENCES `TrainCommanderApi`.`Schedule` (`idSchedule`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Store history of trips associated to a user (only availble ones)';

CREATE USER 'searcher' IDENTIFIED BY 'imasearcher';

GRANT SELECT ON TABLE `TrainCommanderApi`.* TO 'searcher';
CREATE USER 'Admin' IDENTIFIED BY 'TrainCommanderAPI125*';

GRANT ALL ON `TrainCommanderApi`.* TO 'Admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
